### PR TITLE
Proper callback url in plugin description

### PR DESCRIPTION
**Pull request by arulrajnet**
Fix for #13

### CODE REVIEW

**Review by InfoSec812 — COMMENTED** [review]
Please bump the micro-version in the POM and I will start the review period.

**Comment by mostafazh** [comment]
@InfoSec812 do you think this is ready to merge?

**Comment by InfoSec812** [comment]
@mostafazh Sorry for the slow response. I was on a consulting job and then on vacation for a while. I will review and release ASAP.

**Comment by InfoSec812** [comment]
Verified and approved!

**Comment by mostafazh** [comment]
Awesome :+1: Thanks for merging @InfoSec812 :smiley:

**Pull request merged**
